name: biobb_dna_helparms_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_dna==4.1.0
  - nb_conda_kernels
  - matplotlib
  - conda
  - ipywidgets==7.6.6
  - jupyter_client==7.3.2
  - tornado==6.1
  - importlib_metadata
  - ipykernel
